# Generated by Django 4.0.5 on 2022-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(max_length=255, unique=True, verbose_name='Номер')),
                ('make', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('manufacture_year', models.IntegerField(verbose_name='Год выпуска')),
                ('horsepower', models.IntegerField(verbose_name='Количество лошадиных сил')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['registration_plate'],
            },
        ),
        migrations.CreateModel(
            name='CarDBStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип записи')),
                ('car_data', models.JSONField(default=None, verbose_name='Информация об автомобиле')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Статистика базы автомобилей',
                'verbose_name_plural': 'Статистика базы автомобилей',
                'ordering': ['time_create'],
            },
        ),
    ]
